import { db } from '@/lib/db';

async function seedJobs() {
  const sampleJobs = [
    {
      title: 'Frontend Developer',
      company: 'TechCorp Indonesia',
      location: 'Jakarta Selatan',
      type: 'full-time',
      salary: 'Rp 15.000.000 - 25.000.000',
      description: 'Kami mencari Frontend Developer yang berpengalaman untuk bergabung dengan tim kami. Anda akan bertanggung jawab untuk mengembangkan user interface yang menarik dan responsif untuk aplikasi web kami.\n\nTanggung Jawab:\n- Mengembangkan dan mengimplementasikan UI/UX design\n- Kolaborasi dengan backend developer\n- Optimasi performa aplikasi\n- Menulis kode yang clean dan maintainable',
      requirements: 'Persyaratan:\n- Pengalaman minimal 3 tahun sebagai Frontend Developer\n- Mahir menggunakan React.js, Next.js, dan TypeScript\n- Memahami konsep responsive design\n- Pengalaman dengan Tailwind CSS\n- Portfolio yang menunjukkan project yang pernah dikerjakan',
      benefits: 'Keuntungan:\n- Gaji kompetitif\n- BPJS Kesehatan dan Ketenagakerjaan\n- Tunjangan transportasi\n- Bonus performa\n- Peluang pengembangan karir\n- Work from home 2 hari seminggu',
      email: 'hr@techcorp.id',
      category: 'technology',
      imageUrl: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=400&h=300&fit=crop',
      isActive: true,
    },
    {
      title: 'UI/UX Designer',
      company: 'Creative Studio',
      location: 'Bandung',
      type: 'full-time',
      salary: 'Rp 10.000.000 - 18.000.000',
      description: 'Creative Studio mencari UI/UX Designer yang kreatif dan passion dalam design. Anda akan bekerja dengan tim untuk menciptakan pengalaman pengguna yang luar biasa untuk produk digital kami.',
      requirements: 'Persyaratan:\n- Pengalaman minimal 2 tahun sebagai UI/UX Designer\n- Mahir menggunakan Figma, Sketch, atau Adobe XD\n- Memiliki portfolio yang kuat\n- Memahami prinsip design thinking\n- Kemampuan komunikasi yang baik',
      benefits: 'Keuntungan:\n- Gaji kompetitif\n- Asuransi kesehatan\n- Bonus kreatif\n- Kursus dan training\n- Lingkungan kerja yang kreatif',
      email: 'careers@creativestudio.id',
      category: 'design',
      imageUrl: 'https://images.unsplash.com/photo-1559028006-44a36f1157a1?w=400&h=300&fit=crop',
      isActive: true,
    },
    {
      title: 'Digital Marketing Manager',
      company: 'Growth Agency',
      location: 'Jakarta Pusat',
      type: 'full-time',
      salary: 'Rp 12.000.000 - 20.000.000',
      description: 'Growth Agency mencari Digital Marketing Manager untuk memimpin strategi marketing digital klien kami. Anda akan bertanggung jawab atas planning, execution, dan optimization campaign digital.',
      requirements: 'Persyaratan:\n- Pengalaman minimal 4 tahun di digital marketing\n- Mahir menggunakan Google Ads, Facebook Ads\n- Pengalaman dengan SEO dan SEM\n- Kemampuan analisis data yang baik\n- Leadership skills',
      benefits: 'Keuntungan:\n- Gaji kompetitif\n- Bonus performa\n- Asuransi kesehatan\n- Transport allowance\n- Career development program',
      email: 'jobs@growthagency.com',
      category: 'marketing',
      imageUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=300&fit=crop',
      isActive: true,
    },
    {
      title: 'Sales Executive',
      company: 'SalesPro Indonesia',
      location: 'Surabaya',
      type: 'full-time',
      salary: 'Rp 8.000.000 - 15.000.000 + Komisi',
      description: 'SalesPro Indonesia mencari Sales Executive yang dinamis dan target-oriented. Anda akan bertanggung jawab untuk menjual produk dan jasa perusahaan ke perusahaan-perusahaan di area Surabaya dan sekitarnya.',
      requirements: 'Persyaratan:\n- Pengalaman minimal 2 tahun di sales\n- Memiliki network yang luas\n- Kemampuan negosiasi yang baik\n- Target oriented\n- SIM A/C',
      benefits: 'Keuntungan:\n- Gaji pokok + komisi yang menarik\n- BPJS\n- Uang transportasi\n- Bonus tahunan\n- Peluang karir',
      email: 'recruitment@salespro.id',
      category: 'sales',
      imageUrl: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=400&h=300&fit=crop',
      isActive: true,
    },
    {
      title: 'Full Stack Developer',
      company: 'StartupTech',
      location: 'Yogyakarta',
      type: 'remote',
      salary: 'Rp 18.000.000 - 30.000.000',
      description: 'StartupTech mencari Full Stack Developer untuk bergabung dengan tim remote kami. Anda akan bekerja pada project-project menarik dengan teknologi terkini.',
      requirements: 'Persyaratan:\n- Pengalaman minimal 4 tahun sebagai Full Stack Developer\n- Mahir dengan Node.js, React, dan database\n- Pengalaman dengan cloud services (AWS/GCP)\n- Self-motivated dan disciplined\n- Good communication skills',
      benefits: 'Keuntungan:\n- 100% remote work\n- Flexible working hours\n- Gaji yang kompetitif\n- Annual retreat\n- Learning budget\n- Health insurance',
      applyUrl: 'https://startuptech.com/careers/fullstack',
      category: 'technology',
      imageUrl: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=400&h=300&fit=crop',
      isActive: true,
    },
    {
      title: 'Finance Manager',
      company: 'FinanceCorp',
      location: 'Jakarta Utara',
      type: 'full-time',
      salary: 'Rp 25.000.000 - 35.000.000',
      description: 'FinanceCorp mencari Finance Manager yang berpengalaman untuk mengelola keuangan perusahaan. Anda akan bertanggung jawab atas financial planning, analysis, dan reporting.',
      requirements: 'Persyaratan:\n- S1 Akuntansi/Keuangan\n- Pengalaman minimal 5 tahun di finance\n- Mahir menggunakan software akuntansi\n- Certified Public Accountant (CPA) diutamakan\n- Leadership skills',
      benefits: 'Keuntungan:\n- Gaji yang sangat kompetitif\n- Bonus tahunan\n- Asuransi kesehatan premium\n- Tunjangan kendaraan\n- Stock options',
      email: 'hr@financecorp.co.id',
      category: 'finance',
      imageUrl: 'https://images.unsplash.com/photo-1554224154-260325c0591e?w=400&h=300&fit=crop',
      isActive: true,
    },
    {
      title: 'HR Business Partner',
      company: 'PeopleFirst',
      location: 'Tangerang',
      type: 'full-time',
      salary: 'Rp 15.000.000 - 22.000.000',
      description: 'PeopleFirst mencari HR Business Partner untuk menjadi strategic partner dalam mengembangkan organisasi dan talent management.',
      requirements: 'Persyaratan:\n- S1 Psikologi/Hukum/Manajemen\n- Pengalaman minimal 3 tahun di HR\n- Memahami UU Ketenagakerjaan\n- Strong interpersonal skills\n- Strategic thinking',
      benefits: 'Keuntungan:\n- Gaji kompetitif\n- BPJS dan asuransi tambahan\n- Training dan development\n- Career advancement\n- Work-life balance',
      email: 'careers@peoplefirst.id',
      category: 'hr',
      imageUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=300&fit=crop',
      isActive: true,
    },
    {
      title: 'Operations Manager',
      company: 'LogisticsPro',
      location: 'Bekasi',
      type: 'full-time',
      salary: 'Rp 18.000.000 - 28.000.000',
      description: 'LogisticsPro mencari Operations Manager untuk mengelola operasional logistik dan supply chain perusahaan.',
      requirements: 'Persyaratan:\n- S1 Teknik Industri/Manajemen\n- Pengalaman minimal 4 tahun di operations/logistics\n- Leadership skills\n- Problem solving abilities\n- Knowledge of ERP systems',
      benefits: 'Keuntungan:\n- Gaji kompetitif\n- Bonus performa\n- Asuransi kesehatan\n- Tunjangan transportasi\n- Peluang karir',
      email: 'jobs@logisticspro.co.id',
      category: 'operations',
      imageUrl: 'https://images.unsplash.com/photo-1605745341112-85968b19335a?w=400&h=300&fit=crop',
      isActive: true,
    },
    {
      title: 'Backend Developer',
      company: 'API Solutions',
      location: 'Jakarta Selatan',
      type: 'contract',
      salary: 'Rp 20.000.000 - 30.000.000',
      description: 'API Solutions mencari Backend Developer untuk project 6 bulan. Anda akan mengembangkan RESTful API dan microservices.',
      requirements: 'Persyaratan:\n- Pengalaman minimal 3 tahun sebagai Backend Developer\n- Mahir dengan Node.js, Python, atau Java\n- Pengalaman dengan database (SQL/NoSQL)\n- Memahami microservices architecture\n- Experience with Docker/Kubernetes',
      benefits: 'Keuntungan:\n- Project rate yang menarik\n- Flexible working hours\n- Remote work possible\n- Learning opportunities\n- Potential for extension',
      email: 'projects@apisolutions.tech',
      category: 'technology',
      imageUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=400&h=300&fit=crop',
      isActive: true,
    },
    {
      title: 'Content Writer',
      company: 'MediaHub',
      location: 'Jakarta Pusat',
      type: 'part-time',
      salary: 'Rp 5.000.000 - 8.000.000',
      description: 'MediaHub mencari Content Writer untuk membuat konten menarik untuk website dan social media klien.',
      requirements: 'Persyaratan:\n- Pengalaman minimal 1 tahun sebagai content writer\n- Kemampuan menulis yang baik\n- Kreatif dan ide-ide segar\n- Memahami SEO\n- Portfolio tulisan',
      benefits: 'Keuntungan:\n- Flexible working hours\n- Remote work\n- Rate per project yang kompetitif\n- Portfolio building\n- Networking opportunities',
      email: 'writing@mediahub.co.id',
      category: 'marketing',
      imageUrl: 'https://images.unsplash.com/photo-1499488557365-94956c3b705c?w=400&h=300&fit=crop',
      isActive: true,
    }
  ];

  try {
    for (const job of sampleJobs) {
      await db.job.create({
        data: job,
      });
    }
    console.log('Sample jobs seeded successfully!');
  } catch (error) {
    console.error('Error seeding jobs:', error);
  }
}

seedJobs();